### ISSUE TITLE
@com_github_google_ksp .jar files not resolved in windows

### ISSUE THREAD

**Issue by esm-p** [bazelbuild/rules_kotlin#1194] opened 2024-07-15 12:31 UTC
I am trying to build an kotlin application with rules_kotlin_version 1.9.0. There I receive the error message:

```
ERROR: D:/bazel_tmp/33apilyc/external/rules_kotlin/kotlin/compiler/BUILD.bazel:23:17: no such target '@com_github_google_ksp//:symbol-processing-cmdline.jar': target 'symbol-processing-cmdline.jar' not declared in package 
'' defined by D:/bazel_tmp/33apilyc/external/com_github_google_ksp/BUILD.bazel (Tip: use `query "@com_github_google_ksp//:*"` to see all the targets in that package) and referenced by '@rules_kotlin//kotlin/compiler:symbol-processing-cmdline'
```

Executing the recommended query shows only the following targets. All the jar files are missing
```
@com_github_google_ksp//:BUILD.bazel
@com_github_google_ksp//:WORKSPACE  
@com_github_google_ksp//:ksp        
Loading: 0 packages loaded
```

In the bazel_tmp directory D:\bazel_tmp\33apilyc\external\com_github_google_ksp are no .jar files.

I only receive this error in windows, in linux the symbol-processing-*.jar files are availible in the bazel_tmp dir and the build works as expected.

**Comment by restingbull** [comment] 2024-07-15 13:40
Duplicate of #1193

**Closed by restingbull** 2024-07-15 13:40 UTC
