### ISSUE TITLE
Add support for Jetpack Compose

### ISSUE THREAD

**Issue by changusmc** [bazelbuild/rules_kotlin#245] opened 2019-12-17 19:13 UTC
Related to #239 but this issue is to specifically call out support for Jetpack Compose.

From previous conversations in BazelBuild Slack
> I think we can support Jetpack Compose in the kotlin rules without vast changes. It'll need a better kotlin plugin architecture, but nothing that seems insane.
> If you have kt_plugin()  then you should be able to setup a jetpack compose plugin target, then use "plugins=" to consume them, similarly to how you'd do dagger, or auto-value, with java_plugin.

**Comment by cgruber** [comment] 2020-01-15 18:17
This is great.  As mentioned, this should be essentially fixed by #239 but any separate issues can be tracked here.

**Comment by Kernald** [comment] 2020-06-03 10:28
I started taking a look at this, and had a first issue: it looks like the plugin is somehow trying to add itself as a dependency?

```
ERROR: /Users/kernald/dev/monos/java/fr/enoent/experimental/android/compose/BUILD:11:15: in deps attribute of android_binary rule //java/fr/enoent/experimental/android/compose:compose: Dependencies on .jar artifacts are not allowed in Android binaries, please use a java_import to depend on external/maven/v1/https/maven.google.com/androidx/compose/compose-compiler/0.1.0-dev12/compose-compiler-0.1.0-dev12.jar. If this is an implicit dependency then the rule that introduces it will need to be fixed to account for it correctly.. Since this rule was created by the macro 'android_binary', the error might have been caused by the macro implementation
ERROR: Analysis of target '//java/fr/enoent/experimental/android/compose:compose' failed; build aborted: Analysis of target '//java/fr/enoent/experimental/android/compose:compose' failed
```

This is with the following `BUILD`:

```
load("//java/rules:defs.bzl", "kt_android_library")
load("@rules_android//android:rules.bzl", "android_binary", "android_library")

android_library(
    name = "res",
    srcs = [],
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
)

android_binary(
    name = "compose",
    manifest = "AndroidManifest.xml",
    manifest_values = {
        "applicationId": "fr.enoent.android.experimental.compose",
    },
    multidex = "native",
    deps = [
        ":res",
        ":compose_activity",
    ],
)

kt_android_library(
    name = "compose_activity",
    srcs = [
        "ComposeActivity.kt",
    ],
    plugins = [
        "//third_party/androidx/compose:compose_compiler",
    ],
    manifest = "AndroidManifest.xml",
    deps = [
        ":res",
        "@maven//:androidx_appcompat_appcompat",
        "@maven//:androidx_compose_compose_runtime",
    ],
)
```

And `//third_party/androidx/compose/BUILD`:
```
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_compiler_plugin")

kt_compiler_plugin(
    name = "compose_compiler",
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:androidx_compose_compose_compiler",
    ],
)
```

Building the activity target that actually has the plugin dependency also triggers a different error: a version compatibility issue. I'm using kotlinc 1.3.72 (also tried with 1.3.70 with the same result) and compose 0.1.0-dev12. Here's the stacktrace in case I'm missing something:

```
ERROR: /Users/kernald/dev/monos/java/fr/enoent/experimental/android/compose/BUILD:23:19: Compiling Kotlin to JVM //java/fr/enoent/experimental/android/compose:compose_activity_kt { kt: 1, java: 0, srcjars
: 0 } failed (Exit 2)
exception: java.lang.IllegalStateException: The provided plugin androidx.compose.plugins.kotlin.ComposeComponentRegistrar is not compatible with this version of compiler
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:577)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:135)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:175)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:427)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:219)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:150)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:85)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:105)
        at io.bazel.kotlin.compiler.BazelK2JVMCompiler.exec(BazelK2JVMCompiler.kt:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.bazel.kotlin.builder.toolchain.KotlinToolchain$KotlinCliToolInvoker.compile(KotlinToolchain.kt:130)
        at io.bazel.kotlin.builder.tasks.jvm.Compilation_taskKt$compileKotlin$1$1.invoke(compilation_task.kt:151)
        at io.bazel.kotlin.builder.tasks.jvm.Compilation_taskKt$compileKotlin$1$1.invoke(compilation_task.kt)
        at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.executeCompilerTask(CompilationTaskContext.kt:122)
        at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.executeCompilerTask$default(CompilationTaskContext.kt:118)
        at io.bazel.kotlin.builder.tasks.jvm.Compilation_taskKt.compileKotlin(compilation_task.kt:151)
        at io.bazel.kotlin.builder.tasks.jvm.KotlinJvmTaskExecutor$execute$1$$special$$inlined$apply$lambda$1.invoke(KotlinJvmTaskExecutor.kt:52)
        at io.bazel.kotlin.builder.tasks.jvm.KotlinJvmTaskExecutor$execute$1$$special$$inlined$apply$lambda$1.invoke(KotlinJvmTaskExecutor.kt:33)
        at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.execute(CompilationTaskContext.kt:146)
        at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.execute(CompilationTaskContext.kt:138)
        at io.bazel.kotlin.builder.tasks.jvm.KotlinJvmTaskExecutor$execute$1.invoke(KotlinJvmTaskExecutor.kt:50)
        at io.bazel.kotlin.builder.tasks.jvm.KotlinJvmTaskExecutor$execute$1.invoke(KotlinJvmTaskExecutor.kt:33)
        at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.execute(CompilationTaskContext.kt:146)
        at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.execute(CompilationTaskContext.kt:138)
        at io.bazel.kotlin.builder.tasks.jvm.KotlinJvmTaskExecutor.execute(KotlinJvmTaskExecutor.kt:44)
        at io.bazel.kotlin.builder.tasks.KotlinBuilder.executeJvmTask(KotlinBuilder.kt:216)
        at io.bazel.kotlin.builder.tasks.KotlinBuilder.apply(KotlinBuilder.kt:119)
        at io.bazel.kotlin.builder.tasks.PersistentWorker.run(BazelWorker.kt:168)
        at io.bazel.kotlin.builder.tasks.BazelWorker.apply(BazelWorker.kt:74)
        at io.bazel.kotlin.builder.KotlinBuilderMain.main(KotlinBuilderMain.java:28)
Caused by: java.lang.AbstractMethodError: Receiver class androidx.compose.plugins.kotlin.ComposeComponentRegistrar does not define or inherit an implementation of the resolved method 'abstract void regist
erProjectComponents(com.intellij.mock.MockProject, org.jetbrains.kotlin.config.CompilerConfiguration)' of interface org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:569)
        ... 35 more
```

**Comment by cgruber** [comment] 2020-06-03 18:44
So there are two issues here - one is that somehow you're relying on a .jar artifact rather than an import (java_import or kt_jvm_import). It's not clear how that's happening, but that can be tracked down. 

The second issue is that the version of the compose plugin is not compatible with that version of kotlinc, so I would check the versions carefully and make sure they line up - it's possible this second problem is a misleading side-effect of the .jar artifact leakage.

Can you do a bazel query between the plugin jar and teh app binary (`somepath()` I mean) and see what that output is? I'm curious if it really is trying to add itself as a dependency, or if that's a misinterpretation of the error output.

**Comment by Kernald** [comment] 2020-06-03 21:13
This is what query tells:
```
➜ bazel query "somepath(//java/fr/enoent/experimental/android/compose:compose, @maven//:androidx_compose_compose_compiler)"
//java/fr/enoent/experimental/android/compose:compose
//java/fr/enoent/experimental/android/compose:compose_activity
//java/fr/enoent/experimental/android/compose:compose_activity_kt
//third_party/androidx/compose:compose_compiler
@maven//:androidx_compose_compose_compiler
Loading: 4 packages loaded
```

**Comment by Kernald** [comment] 2020-06-03 21:18
Reading #319, I tried wrapping the plugin in a `kt_jvm_import` (I'm fetching it through rules_jvm_external), which gives this path:
```
➜ bazel query "somepath(//java/fr/enoent/experimental/android/compose:compose, @maven//:androidx_compose_compose_compiler)"
//java/fr/enoent/experimental/android/compose:compose
//java/fr/enoent/experimental/android/compose:compose_activity
//java/fr/enoent/experimental/android/compose:compose_activity_kt
//third_party/androidx/compose:compose_compiler
//third_party/androidx/compose:compiler_import
@maven//:androidx_compose_compose_compiler
```

But still causes the same error.

**Comment by Kernald** [comment] 2020-06-14 01:27
Updating to Compose 0.1.0-dev13 fixed the plugin compatibility issue. I can now build the activity target. I guess what's left here is the same issue as #319.

**Comment by alexjlockwood** [comment] 2020-10-28 21:03
@Kernald were you ever able to get compose working with bazel?

**Comment by Kernald** [comment] 2020-10-28 21:07
@alexjlockwood I haven't. My understanding is that old versions of Compose required a patched version of the Kotlin compiler, which might be easy enough to get to work, but these Bazel rules do not work yet with the Kotlin 1.4 compiler, which is now required by Compose. I'm waiting on that to give it another try.

**Comment by alexjlockwood** [comment] 2020-10-28 21:34
@Kernald Interesting. I was expecting the main issue to be that (as far as I know) it's not currently possible to pass target-level `kotlinc` compiler flags? And that would seem to be necessary as Compose requires `-Xuse-ir` to be passed?

**Comment by Kernald** [comment] 2020-10-28 21:42
@alexjlockwood you might be entirely right - I haven't looked into that in quite a while, to be honest.

**Comment by Kernald** [comment] 2020-11-11 06:52
This will most likely be fixed once #384 gets merged.

**Comment by alexjlockwood** [comment] 2020-12-04 02:39
@Kernald I think the error message that you were getting above was due to the fact that you weren't setting the following flag in your `kt_compiler_plugin`:

```
    target_embedded_compiler = True,
```

(At least it seems to be working for me...)

**Comment by Kernald** [comment] 2020-12-08 06:07
I actually hit a totally different error after setting up the compiler plugin properly with the new id etc: for some reason, desugaring kotlin-reflect fails:

```
/home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/external/com_github_jetbrains_kotlin/BUILD.bazel:83:18: Desugaring com_github_jetbrains_kotlin/lib/kotlin-reflect.jar for Android failed (Exit 1): desugar_java8 failed: error executing command 
  (cd /home/kernald/.cache/bazel/_bazel_kernald/551cfa9086d3d42cb8d718a9a97333ef/execroot/fr_enoent && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/k8-py2-opt-exec-2B5CBBC6/bin/external/bazel_tools/tools/android/desugar_java8 @bazel-out/android-armeabi-v7a-fastbuild/bin/external/com_github_jetbrains_kotlin/_dx/kotlin-reflect/kotlin-reflect.jar_desugared.jar-0.params)
Execution platform: @local_config_platform//:host
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:546)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:320)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:240)
        at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1014)
        at com.google.devtools.build.android.desugar.Desugar.runPersistentWorker(Desugar.java:974)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:952)
Target //java/fr/enoent/experimental/android/compose:compose failed to build
```

The only dependency on kotlin-reflect I have is through the compose runtime:
```
bazel query "somepath(//java/fr/enoent/experimental/android/compose:compose, @com_github_jetbrains_kotlin//:kotlin-reflect)"
//java/fr/enoent/experimental/android/compose:compose
//java/fr/enoent/experimental/android/compose:compose_activity
//java/fr/enoent/experimental/android/compose:compose_activity_base
@maven//:androidx_compose_runtime_runtime
@com_github_jetbrains_kotlin//:kotlin-reflect
```

I override `org.jetbrains.kotlin:kotlin-reflect` through `maven_install` to point to `@com_github_jetbrains_kotlin//:kotlin-reflect` instead - but even when using a jar from Maven (just removing the override and updating the pin file), I get the same error (just a different path to the jar).

This is with Bazel 3.7.1 and with the latest (v1.5.0-alpha-1) tag of these rules.

**Comment by alexjlockwood** [comment] 2020-12-09 04:50
@Kernald Not sure if it fixes whatever issue you are seeing, but they did remove kotlin-reflect from compose runtime in this PR here: https://android-review.googlesource.com/c/platform/frameworks/support/+/1507130/ (this was removed in 1.0.0-alpha08)

**Comment by rockwotj** [comment] 2021-01-25 02:57
@Bencodes submitted an example to this repo of how to do this, so this can probably be closed

**Comment by Bencodes** [comment] 2021-01-25 23:57
+1 for closing this issue out now that rules_kotlin has support for compose.

**Comment by Kernald** [comment] 2021-05-20 04:47
Two things should likely be done before closing this:
 - Figuring out what fails in #493 . At the moment, the example is not built on CI, which means we could easily get regressions.
 - Adding a sample test. The way the Compose JUnit test rule is written (with some platform-specific implementations provided through `actual`/`expect`) seems to break with those rules (or I'm missing something, but setting this up is definitely not trivial). Being able to run tests sounds like a strong prerequisite to Compose adoption.

**Closed** 2022-02-04 19:29 UTC
Labels: type: enhancement, component: android, status: open - investigating, P1
