### ISSUE TITLE
Depending on a library via associates= can lead to inconsistent Kotlin JAR

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/rules_kotlin#563] opened 2021-07-22 23:31 UTC
This is related to #211. Using rules_kotlin v1.5.0-beta-2 and Bazel v4.1.0.

I have a `kt_jvm_test` that depends on a `kt_jvm_library` that has another `kt_jvm_library` specified in its `associates` attribute. For simplicity, let's call the test target "Test", the library being tested "SUT", and the library it depends upon "Dep".

 I get a `java.io.FileNotFoundException` in the `KotlinCompile` action that it can't find a specific file inside the `META-INF` of the SUT JAR. The file it's looking for has a `.kotlin_module` extension, and the basename appears to be the default module name of SUT as described in the documentation for the `module_name` attribute.

Digging into the generated `-kt-java.jar` file, I see that the file in `META-INF` has the generated module name of Test whereas the `KotlinCompile` action is expecting the generated module name of SUT.

**Comment by SanjayVas** [comment] 2021-07-24 00:05
I updated the description based on what I think is actually wrong here. Basically, it seems that depending on a library from a kt_jvm_test via associates can sometimes cause that library (or perhaps one of its transitive dependencies) to get a different module name. This means you can get a different module name depending on which target is built first.

Adding a leaf target should never affect the output of one of the libraries it depends upon.

**Comment by cgruber** [comment] 2021-08-06 19:10
So this is curious, becasue any sub-graph of associated libraries should have one, and only one, root node. That has to be first in the build order, because it's a strict dependency also. So given that, there should only be one module. That should be stable, at least in theory.

Could you offer a repro example? I'm very curious why this is happening. It could be a bug in our module setting, but an example might help illustrate it.

**Comment by cgruber** [comment] 2021-08-06 19:23
Can you actually try this with 1.5.0-beta-3? We have a theory of how this might happen unrelated to the associates code itself, because of a way in which Kotlinc was replaying cached information inappropriately and therefore building the wrong metadata into the jar. I don't know that this is htat, but at least, we know that was fixed in beta-3, so it's worth seeing if you still have this problem.

**Comment by SanjayVas** [comment] 2021-08-10 00:08
I can't reproduce on 1.5.0-beta-3

**Comment by cgruber** [comment] 2021-10-01 19:25
Ok. I'm going to close as unreproduceable (at the present release)

**Closed by cgruber** 2021-10-01 19:25 UTC
Labels: type: bug, component: jvm, status: closed - can't repro, P1
