### ISSUE TITLE
[Kotlin 1.5] Compilation error on `private typealias` for android kotlin targets

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/rules_kotlin#549] opened 2021-06-07 23:39 UTC
**Background**
After bumping up kotlin version to 1.5.10, `private typealias` cannot be compiled correctly from android kotlin test targets. According to my test, this issue only happens on bazel for android kotlin rules. Gradle and bazel jvm rules works fine.

**Repro**
exmaple PR to repro this issue https://github.com/bazelbuild/rules_kotlin/pull/548

**Comment by adamfit** [comment] 2021-06-18 14:14
I get this issue in gradle (with different typealias related code). It looks like a kotlin bug to me.

**Comment by nkoroste** [comment] 2021-07-08 20:47
Yes, I think it was fixed in Kotlin v1.5.20 - @ThomasCJY can you please confirm?

**Comment by bjdodson** [comment] 2021-07-31 22:29
Confirmed, fixed in Kotlin 1.5.20+.

**Closed** 2021-08-02 16:55 UTC
