### ISSUE TITLE
Build failure with v1.5.0-alpha-1 and above - Toolchain does not provide ToolchainTypeInfo

### ISSUE THREAD

**Issue by felipecsl** [bazelbuild/rules_kotlin#460] opened 2021-01-21 22:41 UTC
I'm getting the following error while trying to build a simple kotlin library:
```
ERROR: While resolving toolchains for target //src/main/java/path/to/my/project:project_name: 
Target @local_bazel_tools//tools/jdk:runtime_toolchain_type was referenced as a toolchain type, 
but does not provide ToolchainTypeInfo
```

`WORKSPACE` snippet:
```
rules_kotlin_version = "v1.5.0-alpha-3"
rules_kotlin_sha = "eeae65f973b70896e474c57aa7681e444d7a5446d9ec0a59bb88c59fc263ff62"
http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = rules_kotlin_sha,
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/%s/rules_kotlin_release.tgz" % rules_kotlin_version],
)
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()
```

Project `BUILD.bazel`:
```
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "experimental",
    srcs = glob(["*.kt"]),
    visibility = [
        # ... (redacted)
    ],
    deps = [
        # ... (redacted)
    ],
)
```

This works fine with legacy v1.4.0-rc3, so I'm assuming something changed with v1.5.0 that caused this.
I'm new to Bazel so please let me know if there's anything obvious I should be looking for.
Building on intel MacOS. Java v1.8

**Comment by mancini0** [comment] 2021-02-01 23:39
maybe try builiding with the latest Bazel version (I think 4.0.0), you can also try passing in a reference to a well known jdk using the --javabase flag, syntax is :  `bazel run --javabase=@bazel_tools//tools/jdk:remote_jdk11 //myapp:mytests`

**Comment by cgruber** [comment] 2021-08-06 19:48
I can't reproduce this. Are you able to reproduce this with Bazel 4.0/4.1 and kotlin rules 1.5.0-beta-3?

I'm going to close this for now, but feel free to re-open with a repro-case based on a recent release.

**Closed by cgruber** 2021-08-06 19:48 UTC
Labels: P1
