### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt

### ISSUE THREAD

**Issue by mancini0** [bazelbuild/rules_kotlin#333] opened 2020-05-26 23:52 UTC
I hit a run time exception when running a kt_jvm_test that uses Kotlin's "use" facilities:

```
queryRunner.dataSource.connection.use {
                it.autoCommit = false
...
}
```
("use" is similar to Java's try-with-resources, it auto-closes the object upon exit from the block)

**java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt**
	at com.example.cashier.CashierRepoJdbcImpl.handleDeposit(CashierRepoJdbcImpl.kt:177)

I am using the default  legacy-1.3.0  toolchain / repositories mentioned in the README.  I also tried using the example custom toolchain mentioned in the README, with jvm_target set to 1.8, but encounter the same error.

I am not explicitly adding any kotlin libraries to the kt_jvm_test's deps section. Should I be?

**Comment by cgruber** [comment] 2020-06-03 19:30
So, we need to figure out whether this is intended behavior or not, but you should be able to work around this by including the jdk7 stdlib artifact in its deps. There are some configuration questions we need to answer - internally, we explicitly choose which stdlib targets we depend on, but we also have some automation. For now, just explicitly depend on the stdlib as a workaround.

**Comment by cgruber** [comment] 2020-06-03 19:45
Also, can you please try everything out with legacy-1.4.0-rc3 and see if it's still happening? We have made some changes, and it's possible this got fixed in the process.

**Comment by mancini0** [comment] 2020-06-03 20:53
> Also, can you please try everything out with legacy-1.4.0-rc3 and see if it's still happening? We have made some changes, and it's possible this got fixed in the process.

Thanks, I'll try with legacy-1.4.0-rc3 and report back my findings

**Comment by mancini0** [comment] 2020-06-04 02:00
@cgruber  I've tried with legacy-1.4.0-rc3 and encounter the same issue. Here is the repository I made to reproduce the issue: https://github.com/mancini0/reproduce-rules-kotlin-333 . 

I'm using Bazel 3.1.0 \  OpenJdk 11

**Comment by mgenov** [comment] 2020-11-01 09:20
Same on my side. It looks like that kotlin's stdlib is not added to the classpath.

**Comment by chengniansun** [comment] 2021-04-06 02:32
@cgruber 

Could you advise what is the best way to depend on kotlin's stdlib? 

Thanks.

**Comment by cgruber** [comment] 2021-08-06 20:01
Generally I pull in stdlib stuff in via maven. We should look and see whether we can have a better standard situation, so you don't have to, and to avoid having it come from two places - but I harmonize the versions at least with a starlark variable.

**Comment by cgruber** [comment] 2021-08-06 20:29
Every case i've seen has been solved by adding the stdlib-jdk7 artifact. I'm going to close on the basis of this workaround. Please re-open if (with a recent version of bazel and rules_kotlin) this issue is not solved by adding the stdlib-jdk7 dep (via maven, or another source)

**Closed by cgruber** 2021-08-06 20:29 UTC
Labels: type: design, component: common, P2, status: need more information
