### ISSUE TITLE
experimental_strict_kotlin_deps with Kotlin 1.7 always wants to add kotlin-stdlib.jar

### ISSUE THREAD

**Issue by cheister** [bazelbuild/rules_kotlin#939] opened 2023-02-26 21:19 UTC
experimental_strict_kotlin_deps worked great with Kotlin 1.6 but after updating to Kotlin 1.7.x it always gives the message
```
 ** Please add the following dependencies:
/private/var/tmp/_bazel_build/1ef9937daa1a1762ba226d40ef5a90a5/execroot/java/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib.jar to
```
for every `kt_jvm_library` target regardless of whether that dependency is in the deps of the target or not.

**Comment by restingbull** [comment] 2023-03-03 21:05
Duplicate of #930

**Closed by restingbull** 2023-03-03 21:05 UTC
