### ISSUE TITLE
`exports` in kt_jvm_library doesn't work

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/rules_kotlin#226] opened 2019-11-08 22:48 UTC
Example:

```
Test.kt
package com.example.bazel

import com.google.common.base.Joiner

class Test {
    fun test() {
        val a = Joiner.on(",")
    }
}

==========================
BUILD
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "test",
    visibility = ["//visibility:public"],
    srcs = ["java/com/example/bazel/Test.kt"],
    exports = ["@maven//:com_google_guava_guava_28_1_android"]
)
```

Running ` bazel build //src/main:test` report error `error: unresolved reference: google`
If I switch to use `deps` instead of `exports` the build will be successful

```
rule version:
rules_kotlin_version = "legacy-1.3.0-rc1"
rules_kotlin_sha = "9de078258235ea48021830b1669bbbb678d7c3bdffd3435f4c0817c921a88e42"
```

**Comment by nkoroste** [comment] 2019-11-12 22:53
This is working as intended:
> Important: an exported rule is not a regular dependency. Sticking to the previous example, if B exports C and wants to also use C, it has to also list it in its own deps.

from: https://docs.bazel.build/versions/master/be/java.html#java_library.exports

**Comment by cgruber** [comment] 2019-11-26 19:05
Closing as won't fix, since this is the intended behavior.

**Closed by cgruber** 2019-11-26 19:05 UTC
Labels: P1, component: common, status: closed - wontfix, type: bug
