### ISSUE TITLE
kotlin rules - android import kotlinx.android.synthetic.main.fragment_main_web_view.view.*

### ISSUE THREAD

**Issue by salim-boudriiya** [bazelbuild/rules_kotlin#225] opened 2019-10-30 11:14 UTC
Hi @cgruber,

I am working on an android project with bazel, this project uses kotlin as a programming language, I just updated the kotlin rules to version legacy-1.3.0-rc1.

But I still have that error:

ESPC006863: Globile-Software smba $ bazel build webviewbridgelib / src / main: bazel_webviewbridgelib
INFO: Analyzed target // webviewbridgelib / src / main: bazel_webviewbridgelib (1 packages loaded, 82 targets configured).
INFO: Found 1 target ...
BUG: / Users / smba / Globile-Software / webviewbridgelib / src / main / BUILD: 29: 1: Compiling Kotlin to JVM // webviewbridgelib / src / main: bazel_kt_webviewbridgelib_kt {kt: 20, java: 0, srcjars: 0} failed (Exit 1)
webviewbridgelib / src / main / java / com / santander / globile / webviewbridgelib / view / MainWebViewFragment.kt: 35: 16: error: unresolved reference: android
import kotlinx.android.synthetic.main.fragment_main_web_view.view. *

Please, could you tell me when we will be able to work with a version that solves the issue of android-kotlin extensions.

Best Regards

**Comment by cgruber** [comment] 2019-10-30 17:56
The current rules do not support kotlin plugins other than kapt3 via the java_plugins infrastructure.  We have an initial version that specifically enables android extensions, and hopefully we'll be adding a pull request for it later this week.  

Closing this as a duplicate of #145

**Closed by cgruber** 2019-10-30 17:56 UTC
