### ISSUE TITLE
Does Kotlin Serialization support work?

### ISSUE THREAD

**Issue by jongerrish** [bazelbuild/rules_kotlin#313] opened 2020-04-12 02:55 UTC
According to https://github.com/Kotlin/kotlinx.serialization, the serialization compiler plugin is built into the Kotlin compiler since v1.3.X

"""
Starting from Kotlin 1.3-RC2, serialization plugin is shipped with the rest of Kotlin compiler distribution, and the IDEA plugin is bundled into the Kotlin plugin.
"""

...but I'm seeing compilation errors because the generated *.serializer() methods are missing.

I was expecting this to happen without any additional configuration, is there something I'm missing here?

kt_jvm_library(
    name = "serialization_lib",
    srcs = glob(["**/*.kt"]),
    deps = [
        artifact("org.jetbrains.kotlinx:kotlinx-serialization-runtime"),
    ],
)

**Comment by IljaKroonen** [comment] 2020-04-12 09:31
There is some basic support for compiler plugins, through the `kt_compiler_plugin` rule as you can see in the Readme. It's not part of a release yet, so you would have to use the master version of the rules.

**Comment by jongerrish** [comment] 2020-04-12 15:01
Hi @IljaKroonen yeah I saw that, so the serialization plugin that ships with the compiler doesn't seem to be enabled by default. It does comes as part of the compiler distribution as kotlinx-serialization-compiler-plugin.jar but its't placed on the classpath in the kotlinc script. What's the best way to get that jar into the deps attribute of `kt_compiler_plugin`... is there a short hand to refer to jars that are part of the toolchain? I'm not sure what the id/options might be either for it are, would they refer to something in the jars manifest or services? I'd be happy to submit a PR with tests / docs to the project if I can get this working.

**Comment by IljaKroonen** [comment] 2020-04-12 15:59
You could get the jar file some other way, or you'd have to add something like this:

```
kt_jvm_import(
    name = "kotlinx-serialization-compiler-plugin",
    jar = "lib/kotlinx-serialization-compiler-plugin.jar",
)
```

To this file: https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/repositories/BUILD.com_github_jetbrains_kotlin

This would break the plugin for compiler version that don't have the jar though.

**Comment by jongerrish** [comment] 2020-04-12 21:34
Well, that works :-)

No id or options necessary.

How would you like me to proceed on this? I'm happy to submit a PR. I'm not sure how you'd want to handle the absence of the serialization plugin on older < 1.3 compilers. There's probably precedence with the other bundled compiler plugins although I'm not sure what version they were added or what min version of the compiler you want to support.

**Comment by utikeev** [comment] 2020-04-13 08:55
Serialization plugin is also available in [Maven](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-serialization-unshaded) and can be used accordingly, so you won't have to break it for older compiler versions:
```
kt_compiler_plugin(
    name="serialization",
    deps = [
        "@maven//:org_jetbrains_kotlin_kotlin_serialization_unshaded",
    ],
)
```

---------

@IljaKroonen, I wonder, if you'd support generated methods in Bazel IntelliJ plugin, so it will resolve `.serializer()` methods? This can be done by adding 
```
<array>
    <option value="$KOTLIN_BUNDLED$/lib/PLUGIN_JAR_NAME.jar" />
</array>
```
to `component -> facet -> configuration -> compilerArguments -> pluginClasspaths`.
I know, that there is a problem with Bazel projects currently having single module, but I guess, it's fine to add it, if at least one module has it. It's better than unresolved references.

**Comment by cgruber** [comment] 2020-04-13 19:56
I would suggest using the maven version for now (as long as you're carefully version-pinning the maven version to the same version as your kotlinc ). 

At this point, I don't think we're really supporting pre-1.3 compilers. If we need to, then it's a separate feature to more aggressively test it. The layout is slightly different for pre-1.3 compilers anyway.

I need to check, but as I recall, also, the rules set up a repository for the kotlinc toolchain, and that should include an import for the available jars already.  But using the maven release versions should also be fine.

**Comment by cgruber** [comment] 2020-04-13 19:58
@utikeev - can you file a bug to include plugin jars in the metadata we provide to intellij? I'm not 100% sure it's a change we do here, or in bazelbuild/intellij, but we should track it.

**Comment by cgruber** [comment] 2020-04-13 19:58
Also, I'll be releasing an RC of rules_kotlin-1.4.0 shortly that includes the plugin capability.

**Comment by utikeev** [comment] 2020-04-13 20:07
> @utikeev - can you file a bug to include plugin jars in the metadata we provide to intellij? I'm not 100% sure it's a change we do here, or in bazelbuild/intellij, but we should track it.

[Done](https://github.com/bazelbuild/intellij/issues/1773).

**Comment by cgruber** [comment] 2020-04-13 20:14
For now, closing this issue as won't-fix/working-as-intended. If there are issues where it's NOT working as intended once the RC is released please file a specific bug with appropriate details there.

**Closed by cgruber** 2020-04-13 20:14 UTC
Labels: P2, component: common, status: closed - wontfix, type: enhancement

**Comment by jongerrish** [comment] 2020-04-14 01:42
Hi @cgruber I think we'd still need to add the jar export as mentioned in  https://github.com/bazelbuild/rules_kotlin/issues/313#issuecomment-612637783 - I can send a PR if you're open to it?

**Comment by cgruber** [comment] 2020-04-14 03:49
@jongerrish - sure, though I see other compiler plugins already listed - this feels like it could be generally added (scoop up all the lib/*-compiler-plugin.jar files and export them). But of course, feel free to send a PR. 

That said, it's strictly not necessary, insofar as these jars are also published via maven, if I'm not mistaken.
